version: "3"
services:
  gremlin-server:
    build:
      context: "./simple"
      dockerfile: Dockerfile
      args:
        - GREMLIN_SERVER=${GREMLIN_SERVER}
    command : ["conf/gremlin-server.yaml"]
    ports:
      - "8182:8182"
  gremlin-server-secure:
    build:
      context: "./credentials"
      dockerfile: Dockerfile
      args:
        - GREMLIN_SERVER=${GREMLIN_SERVER}
    command : ["conf/gremlin-server-credentials.yaml"]
    ports:
      - "8183:8182"
  janusgraph:
    image: janusgraph/janusgraph:latest
    environment:
      - janusgraph.graph.set-vertex-id=true
      - janusgraph.graph.allow-custom-vid-types=true
      - JANUS_PROPS_TEMPLATE=inmemory
    ports:
      - "8184:8182"
  